services:
  - type: web
    name: fantasy-betting
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: fantasy-betting-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: fantasy-betting-db
    databaseName: fantasy_betting
    region: frankfurt
    plan: free
